import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const files = Object.fromEntries(await Promise.all(['index.js', 'src/ui.js', 'src/application.js', 'src/repository.js', 'src/context-compiler.js', 'src/sillytavern-adapter.js', 'src/generation-transaction.js'].map(async file => [file, await readFile(new URL(file, root), 'utf8')])));
const installedAdapter = new URL('src/sillytavern-adapter.js', 'file:///SillyTavern/public/scripts/extensions/third-party/candy-w-rpg-console/');
assert.equal(new URL('../../../../extensions.js', installedAdapter).pathname, '/SillyTavern/public/scripts/extensions.js');
assert.equal(new URL('../../../../../script.js', installedAdapter).pathname, '/SillyTavern/public/script.js');
assert.match(files['src/sillytavern-adapter.js'], /context\.generate\('normal', \{ automatic_trigger: true, depth: 1 \}\)/);
assert.match(files['src/sillytavern-adapter.js'], /onlineStatus === 'no_connection'/);
assert.match(files['src/sillytavern-adapter.js'], /chatKind\(\) === 'group'/);
assert.match(files['src/sillytavern-adapter.js'], /isGenerating\(\)/);
assert.match(files['src/sillytavern-adapter.js'], /setSendButtonState\(true\)/);
assert.match(files['src/sillytavern-adapter.js'], /context\.deactivateSendButtons\(\)/);
assert.match(files['src/sillytavern-adapter.js'], /context\.activateSendButtons\(\)/);
assert.match(files['src/sillytavern-adapter.js'], /runGenerationTransaction/);
assert.match(files['src/generation-transaction.js'], /eventSource\.on\(stoppedEvent, onStopped\)/);
assert.match(files['src/generation-transaction.js'], /removeListener\(stoppedEvent, onStopped\)/);
assert.match(files['src/sillytavern-adapter.js'], /context\.saveMetadata\(\)/);
assert.match(files['src/application.js'], /characterId/);
assert.match(files['src/repository.js'], /structuredClone\(metadata\[METADATA_KEY\]\)/);
assert.doesNotMatch(files['src/ui.js'], /chatMetadata|setExtensionPrompt|generate\(/);
assert.doesNotMatch(files['src/application.js'], /chatMetadata|setExtensionPrompt|generate\(/);
assert.doesNotMatch(`${files['index.js']}\n${files['src/ui.js']}\n${files['src/application.js']}`, /from ['"].*script\.js/);
assert.doesNotMatch(`${files['src/repository.js']}\n${files['src/context-compiler.js']}\n${files['src/generation-transaction.js']}`, /getContext|setExtensionPrompt/);
assert.equal((files['src/sillytavern-adapter.js'].match(/setExtensionPrompt\(/g) ?? []).length, 1, 'one adapter-owned context slot');
assert.doesNotMatch(Object.values(files).join('\n'), /fetch\(|#send_textarea|dispatchEvent\(new Event\(['"]input/);
console.log('architecture tests passed');
