import test from 'node:test';
import assert from 'node:assert/strict';
import {FOG_HARBOR_SCENARIO as original} from '../src/scenarios/index.js';
import {insertChapter} from '../src/domain/chapter-insertion.js';
import {createDirectorState,prepareOpeningTurn,commitTurn,prepareActionTurn,listAvailableMoves,stateMatchesScenario} from '../src/domain/director-state.js';
const chapter={title:'雨中的来信',summary:'在风暴中寻找送信人。',connection:'路边有人请求帮助。',scenes:[{title:'避雨亭',description:'送信人在亭下等候。',location:'码头亭',timeLabel:'此刻',objective:'接过来信',action:'接过来信',consequence:'你收好来信，返回原路。',minutes:2}]};
function playing(){const s=createDirectorState(original,{name:'旅人',concept:'',relationship:'',attributes:{body:0,insight:0,rapport:0}});const p=prepareOpeningTurn(s,original);return commitTurn(p.state,original,p.turn,{performance:'暴雨中，你走入港城。'});}
function advance(state,scenario,id){const m=listAvailableMoves(state,scenario).find(m=>m.id===id);assert.ok(m,`available ${id}`);const p=prepareActionTurn(state,scenario,{transactionId:'tx_'+state.revision,baseRevision:state.revision,actionId:id,attribute:null,summary:'继续前进'});return commitTurn(p.state,scenario,p.turn,{performance:'你和同行者继续前行。'});}
test('immediate chapter preserves player and history, returns to selected scene',()=>{const state=playing();const result=insertChapter(original,state,{chapter,mode:'now',returnSceneId:state.hidden.currentSceneId});assert.ok(stateMatchesScenario(result.state,result.scenario));assert.deepEqual(result.state.player,state.player);assert.deepEqual(result.state.history,state.history);assert.deepEqual(result.state.hidden.clock,state.hidden.clock);assert.equal(result.state.public.scene.title,'避雨亭');const m=listAvailableMoves(result.state,result.scenario)[0];const end=advance(result.state,result.scenario,m.id);assert.equal(end.hidden.currentSceneId,state.hidden.currentSceneId);assert.equal(original.scenes.some(s=>s.title==='避雨亭'),false);});
test('after chapter insertion defers original exit facts and returns to each original destination',()=>{const state=playing();const {scenario,state:inserted}=insertChapter(original,state,{chapter,mode:'after'});assert.equal(inserted.hidden.currentSceneId,state.hidden.currentSceneId);const act=original.scenes.find(s=>s.id===state.hidden.currentSceneId).actId;const exits=original.scenes.filter(s=>s.actId===act).flatMap(s=>s.moves).filter(m=>!m.checkId&&(m.endingId||m.nextSceneId&&original.scenes.find(s=>s.id===m.nextSceneId).actId!==act));assert.ok(exits.length);for(const exit of exits){const changed=scenario.scenes.flatMap(s=>s.moves).find(m=>m.id===exit.id);assert.notEqual(changed.nextSceneId,exit.nextSceneId);assert.deepEqual(changed.revealSecretIds,[]);const endScene=scenario.scenes.find(s=>s.id===changed.nextSceneId);const returnMove=endScene.moves.find(m=>m.conditions.allFacts[0]===changed.hiddenPatch.occurredFactIds[0]);assert.equal(returnMove.nextSceneId,exit.nextSceneId);assert.equal(returnMove.endingId,exit.endingId);assert.deepEqual(returnMove.hiddenPatch,exit.hiddenPatch);}});
test('invalid draft and missing return destination fail without mutating original',()=>{const state=playing();assert.throws(()=>insertChapter(original,state,{chapter:{...chapter,scenes:[]},mode:'now',returnSceneId:state.hidden.currentSceneId}));assert.throws(()=>insertChapter(original,state,{chapter,mode:'now',returnSceneId:'missing'}));assert.equal(state.revision,1);});
