import test from 'node:test';
import assert from 'node:assert/strict';
import {DirectorApplication} from '../src/application/index.js';
import {PerChatRepository} from '../src/persistence/per-chat-repository.js';
import {validateDirectorState,validateScenario} from '../src/domain/index.js';
import {FOG_HARBOR_SCENARIO as scenario} from '../src/scenarios/index.js';
import {FakeOfficialAdapter} from './support/fake-official-adapter.mjs';
import {validatePlan,authoringInput} from '../src/protocol/scenario-authoring.js';
import {validateChapterOutline} from '../src/domain/chapter-outline.js';
function setup(){const adapter=new FakeOfficialAdapter();adapter.selectSingle('guide.png','modules');const repository=new PerChatRepository({adapter,validateState:validateDirectorState,validateScenario});const app=new DirectorApplication({adapter,repository}).start();return {adapter,repository,app};}
test('library deletion and restoration preserve active snapshot, setup and previous version',async()=>{const {adapter,repository,app}=setup();try{const copy=await app.copyScenario({id:scenario.id});await app.createCampaign({scenarioId:copy.id,player:{name:'旅人',concept:'',relationship:'',attributes:{body:0,insight:0,rapport:0}}});const before=structuredClone(adapter.currentChatMetadata());await app.deleteScenario({id:copy.id,expectedHash:copy.hash});assert.ok(!app.listScenarios().some(s=>s.id===copy.id));assert.deepEqual(adapter.currentChatMetadata(),before);assert.equal(repository.loadScenario().hash,copy.hash);assert.ok(app.getDeletedScenarios().some(s=>s.id===copy.id));await app.restoreDeletedScenario(copy.id);assert.equal(app.getScenarioDocument({id:copy.id}).hash,copy.hash);assert.deepEqual(adapter.currentChatMetadata(),before);await app.deleteScenario({id:scenario.id,expectedHash:scenario.hash});assert.ok(!app.listScenarios().some(s=>s.id===scenario.id));await app.restoreDeletedScenario(scenario.id);assert.ok(app.listScenarios().some(s=>s.id===scenario.id));assert.equal(adapter.rawPrompts.length,0);}finally{await app.destroy();}});
test('chapter outline count, IDs, titles and order are enforced during planning',()=>{const adapter=new FakeOfficialAdapter(),draft=structuredClone(scenario);delete draft.hash;adapter.enqueueScenario(draft);const plan=JSON.parse(adapter.rawDecisions[0]);const chapterOutline=scenario.acts.map(a=>({id:a.id,title:a.title,summary:a.summary}));const source=authoringInput('revision',{title:scenario.public.title,original:scenario,request:'调整章节顺序',chapterOutline});validatePlan(plan,source);assert.throws(()=>validatePlan({...plan,acts:[...plan.acts].reverse()},source),/章节/);assert.throws(()=>validatePlan({...plan,acts:plan.acts.slice(1)},source),/章节/);assert.throws(()=>validateChapterOutline([chapterOutline[0],chapterOutline[0]]),/重复/);});
test('reordered chapters generate a review before replacing the library, preserving the live journey',async()=>{const {adapter,repository,app}=setup();try{
 const doc=await app.copyScenario({id:scenario.id});await app.createCampaign({scenarioId:doc.id,player:{name:'旅人',concept:'',relationship:'',attributes:{body:0,insight:0,rapport:0}}});const before=structuredClone(adapter.currentChatMetadata());
 const original=app.library.get(doc.id),draft=structuredClone(original);delete draft.hash;draft.contentVersion='1.0.1';
 draft.acts=[draft.acts[1],draft.acts[0],draft.acts[2]].map((a,i)=>({...a,number:i+1}));draft.scenes=draft.acts.flatMap(a=>draft.scenes.filter(s=>s.actId===a.id));draft.startSceneId=draft.scenes[0].id;
 for(let i=0;i<draft.scenes.length-1;i++){draft.scenes[i].moves.push({id:'order_link_'+i,label:'沿新章节前行',description:'前往下一段故事',clockAdvance:0,attribute:null,checkId:null,conditions:{allFacts:[],anyFacts:[],notFacts:[]},mustHappen:['前往下一段故事。'],revealSecretIds:[],publicPatch:{objective:null,knownPeopleIds:[],knownClueIds:[],itemIds:[],crisisIds:[]},hiddenPatch:{occurredFactIds:[],setVariables:{}},nextSceneId:draft.scenes[i+1].id,endingId:null});}
 const chapterOutline=draft.acts.map(a=>({id:a.id,title:a.title,summary:a.summary}));adapter.enqueueScenario(draft,{includePlayer:false});
 await app.reviseScenario({id:doc.id,expectedHash:doc.hash,request:'按新顺序衔接',chapterOutline});const review=app.authoring.read(adapter.currentChatIdentity()).review;assert.deepEqual(review.acts.map(a=>a.id),chapterOutline.map(a=>a.id));assert.equal(app.getScenarioDocument({id:doc.id}).hash,doc.hash);assert.deepEqual(adapter.currentChatMetadata(),before);
 await app.acceptScenarioRevision({jobId:app.getAuthoringJob().jobId});assert.equal(app.getScenarioDocument({id:doc.id}).hash,review.hash);assert.equal(repository.loadScenario().hash,doc.hash);assert.deepEqual(adapter.currentChatMetadata(),before);
 }finally{await app.destroy();}});
