import { finalizeScenario } from '../domain/scenario-schema.js';

const emptyConditions = () => ({ allFacts: [], anyFacts: [], notFacts: [] });
const publicPatch = (overrides = {}) => ({
    objective: null,
    knownPeopleIds: [],
    knownClueIds: [],
    itemIds: [],
    crisisIds: [],
    ...overrides,
});
const hiddenPatch = (occurredFactIds = [], setVariables = {}) => ({ occurredFactIds, setVariables });
const move = (id, label, description, overrides = {}) => ({
    id,
    label,
    description,
    clockAdvance: 10,
    attribute: null,
    checkId: null,
    conditions: emptyConditions(),
    mustHappen: [description],
    revealSecretIds: [],
    publicPatch: publicPatch(),
    hiddenPatch: hiddenPatch(),
    nextSceneId: null,
    endingId: null,
    ...overrides,
});

const draft = {
    schema: 'candy-w-rpg-director/scenario/v2',
    version: 2,
    id: 'fog-harbor-zero-tide',
    contentVersion: '2.0.0',
    hash: '',
    public: {
        title: '雾港零点潮',
        tagline: '午夜的潮门只允许一座城区被完整保住。',
        summary: '暴雨封港的夜里，一枚失窃的压力盘把你引向旧港深处。零点前，你必须在互不信任的人之间找到真相，并决定洪水流向哪里。',
        tone: '悬疑 · 灾难 · 关系',
        duration: '约 2–3 小时',
        symbol: '≋',
        tags: ['暴雨', '港城', '倒计时', '多结局'],
    },
    coreFacts: [
        { id: 'storm_unavoidable', text: '零点风暴与海潮不可避免，不能被任何角色或判定取消。' },
        { id: 'gate_three_routes', text: '潮门只能把洪水导向旧港、仓区，或执行高风险分流。' },
        { id: 'wei_sabotage', text: '魏朔破坏了潮门自动系统并伪造调令，目的是逼管理局优先保仓区。' },
        { id: 'lin_prisoner', text: '工程师林岚被囚在钟楼，并把分流所需的压力盘藏在报时机下。' },
        { id: 'explosion_fixed', text: '23:10 的旧泵房爆炸必定发生；此前行为只能改变伤亡与后续通路。' },
        { id: 'evacuation_list_withheld', text: '旧港疏散名单被魏朔扣下，居民尚未得到完整撤离通知。' },
        { id: 'tang_unaware', text: '巡防长唐岑最初不知道调令是伪造的。' },
        { id: 'character_no_secret_identity', text: '当前角色卡角色没有剧本擅自添加的秘密身份或命定血统。' },
    ],
    secrets: [
        {
            id: 'secret_forgery',
            title: '伪造调令',
            fact: '魏朔使用已故港务长的旧印伪造了封锁旧港的调令。',
            revealText: '调令上的印泥来自早已封存的旧印，而签发时间晚于港务长死亡时间。',
            leakPhrases: ['魏朔伪造调令', '已故港务长的旧印'],
        },
        {
            id: 'secret_pressure_disk',
            title: '压力盘位置',
            fact: '林岚把压力盘藏在钟楼报时机的配重盒中。',
            revealText: '报时机配重盒里藏着缺失的潮门压力盘，上面留有林岚的检修记号。',
            leakPhrases: ['压力盘藏在钟楼', '报时机的配重盒'],
        },
        {
            id: 'secret_evacuation',
            title: '被扣下的疏散名单',
            fact: '魏朔扣住名单，是为了让分流到旧港看起来必然造成更大伤亡。',
            revealText: '完整名单一直锁在港务办公室，旧港仍来得及分区撤离。',
            leakPhrases: ['魏朔扣住疏散名单', '完整名单锁在港务办公室'],
        },
        {
            id: 'secret_sabotage',
            title: '自动系统破坏',
            fact: '所谓雷击故障其实是人为剪断反馈线，切口与魏朔工具上的缺口吻合。',
            revealText: '反馈线不是被雷烧断，而是被同一把有缺口的钳子剪断。',
            leakPhrases: ['魏朔剪断反馈线', '人为破坏自动系统'],
        },
    ],
    npcs: [
        {
            id: 'npc_lin',
            name: '林岚',
            role: '潮门工程师',
            publicRelation: '曾与当前角色共同参与旧港检修',
            publicDescription: '冷静、克制，即使受困仍先确认潮门数据。',
            hiddenGoal: '保住尽可能多的人，并让破坏证据留下来。',
            agenda: [
                { thresholdId: 't_2230', action: '从钟楼线路发出一段断续检修码。', factId: 'agenda_lin_signal' },
                { thresholdId: 't_2350', action: '若仍无人救援，尝试自行拆开报时机。', factId: 'agenda_lin_escape' },
            ],
        },
        {
            id: 'npc_wei',
            name: '魏朔',
            role: '港务理事',
            publicRelation: '以封港总协调人的身份下令',
            publicDescription: '语气笃定，始终把仓区物资称作整座城的命脉。',
            hiddenGoal: '让仓区毫发无损，并把旧港损失包装成自然灾害。',
            agenda: [
                { thresholdId: 't_2200', action: '命人封存港务办公室档案。', factId: 'agenda_wei_seal' },
                { thresholdId: 't_2310', action: '借爆炸销毁自动系统的维修记录。', factId: 'agenda_wei_burn' },
                { thresholdId: 't_2350', action: '前往控制室强行选择仓区优先方案。', factId: 'agenda_wei_control' },
            ],
        },
        {
            id: 'npc_mu',
            name: '小牧',
            role: '旧港信使',
            publicRelation: '在海关门外主动拦住你',
            publicDescription: '浑身湿透，抱着一只装满未送出通知的邮袋。',
            hiddenGoal: '把疏散消息送进旧港，并找到失踪的姐姐林岚。',
            agenda: [
                { thresholdId: 't_2230', action: '独自穿过巡防线向旧港送信。', factId: 'agenda_mu_run' },
                { thresholdId: 't_2330', action: '开始敲响旧港手摇警钟。', factId: 'agenda_mu_alarm' },
            ],
        },
        {
            id: 'npc_tang',
            name: '唐岑',
            role: '巡防长',
            publicRelation: '奉调令封锁通往旧港的路',
            publicDescription: '严格执行程序，但会认真核对能拿出证据的人。',
            hiddenGoal: '维持秩序并避免部下成为政治命令的替罪羊。',
            agenda: [
                { thresholdId: 't_2310', action: '把一队人调去爆炸的泵房救援。', factId: 'agenda_tang_rescue' },
                { thresholdId: 't_2350', action: '若仍未见证据，执行封死旧港闸道的命令。', factId: 'agenda_tang_lock' },
            ],
        },
    ],
    clocks: [{
        id: 'zero_tide',
        label: '零点风暴潮',
        startMinute: 1300,
        endMinute: 1440,
        thresholds: [
            { id: 't_2200', minute: 1320, publicWarning: '港区广播宣布一级封锁。', hiddenEvent: '魏朔开始封存能证明伪造的档案。', factId: 'time_2200', setVariables: { office_sealed: true } },
            { id: 't_2230', minute: 1350, publicWarning: '钟楼传来不合时序的三短一长钟声。', hiddenEvent: '林岚发出检修码，小牧开始自行送信。', factId: 'time_2230', setVariables: { lin_signal_sent: true } },
            { id: 't_2310', minute: 1390, publicWarning: '旧泵房爆炸，整片港区短暂断电。', hiddenEvent: '固定爆炸发生，魏朔借机焚毁部分记录。', factId: 'time_2310', setVariables: { pump_exploded: true } },
            { id: 't_2330', minute: 1410, publicWarning: '旧港的手摇警钟开始连续鸣响。', hiddenEvent: '最靠近钟声的居民开始自发撤离。', factId: 'time_2330', setVariables: { partial_evacuation: true } },
            { id: 't_2350', minute: 1430, publicWarning: '潮门控制室只剩最后一次人工切换机会。', hiddenEvent: '魏朔与唐岑分别执行最后的幕后行动。', factId: 'time_2350', setVariables: { final_window: true } },
            { id: 't_0000', minute: 1440, publicWarning: '零点风暴潮撞上外堤。', hiddenEvent: '潮门必须按已提交状态结算，不能继续拖延。', factId: 'time_0000', setVariables: { tide_arrived: true } },
        ],
    }],
    knowledge: {
        people: [
            { id: 'person_mu', name: '小牧', relation: '旧港信使', detail: '她带着未送出的疏散通知，并在寻找姐姐林岚。', status: '与你一同行动或继续向旧港送信', anchors: ['小牧', '旧港信使'] },
            { id: 'person_lin', name: '林岚', relation: '潮门工程师', detail: '掌握人工分流方法，最后被人看见时正前往钟楼。', status: '下落不明', anchors: ['林岚', '潮门工程师'] },
            { id: 'person_wei', name: '魏朔', relation: '港务理事', detail: '下令优先保全仓区，并要求所有人服从封港调令。', status: '正在港区协调封锁', anchors: ['魏朔', '港务理事'] },
            { id: 'person_tang', name: '唐岑', relation: '巡防长', detail: '执行旧港封锁，愿意核查可验证的证据。', status: '驻守巡防线', anchors: ['唐岑', '巡防队'] },
        ],
        clues: [
            { id: 'clue_notice', name: '未送出的疏散通知', detail: '通知要求旧港居民在 23:30 前分区撤离，但没有管理局印章。', anchors: ['疏散通知', '旧港'] },
            { id: 'clue_forged_order', name: '时间不可能的调令', detail: '签发时间与印章主人的死亡记录互相矛盾。', anchors: ['封港调令', '港务办公室'] },
            { id: 'clue_cut_wire', name: '被剪断的反馈线', detail: '整齐切口证明自动系统并非因雷击失效。', anchors: ['潮门反馈线', '旧泵房'] },
            { id: 'clue_signal', name: '三短一长检修码', detail: '这是工程师请求从钟楼线路实施人工接管的信号。', anchors: ['三短一长', '钟楼'] },
            { id: 'clue_pressure_disk', name: '潮门压力盘', detail: '人工分流的必要部件，带有林岚的检修标记。', anchors: ['压力盘', '潮门控制室'] },
        ],
        items: [
            { id: 'item_postbag', name: '旧港邮袋', detail: '装着按街区分好的疏散通知。', anchors: ['旧港邮袋'] },
            { id: 'item_order_copy', name: '调令副本', detail: '可与档案中的印章与时间记录比对。', anchors: ['调令副本'] },
            { id: 'item_pressure_disk', name: '压力盘', detail: '能让潮门在零点前执行一次人工分流。', anchors: ['压力盘'] },
        ],
        crises: [
            { id: 'crisis_tide', name: '零点风暴潮', detail: '风暴不可避免，潮门必须选择洪水去向。', urgency: '21:40 → 00:00', anchors: ['零点风暴潮', '潮门'] },
            { id: 'crisis_lockdown', name: '旧港封锁', detail: '巡防线阻止居民收到完整疏散通知。', urgency: '封锁正在收紧', anchors: ['旧港封锁'] },
            { id: 'crisis_pump', name: '旧泵房故障', detail: '自动系统失效，泵房温度和压力持续上升。', urgency: '23:10 前', anchors: ['旧泵房'] },
        ],
    },
    acts: [
        { id: 'act_one', number: 1, title: '封港令', summary: '在暴雨与封锁之间找到第一条可靠线索。', sceneIds: ['customs_gate', 'port_office', 'old_pump'] },
        { id: 'act_two', number: 2, title: '钟声之前', summary: '让证据、疏散与被困的工程师赶在幕后计划前发生作用。', sceneIds: ['patrol_line', 'bell_tower'] },
        { id: 'act_three', number: 3, title: '零点潮门', summary: '用已经付出的代价决定洪水去向。', sceneIds: ['control_room', 'leave_harbor'] },
    ],
    scenes: [
        {
            id: 'customs_gate', actId: 'act_one', title: '雨中的海关门',
            description: '21:40，封港铁门正在落下。小牧抱着未送出的邮袋拦住你，远处潮门警灯第一次转红。',
            location: '雾港海关门', timeLabel: '21:40', objective: '决定先追查调令、检查故障，还是放弃介入。',
            anchors: ['雾港海关门', '小牧', '零点风暴潮', '潮门'], entryFacts: ['entered_customs_gate'],
            moves: [
                move('gate_to_office', '追查封港调令', '小牧把调令副本和邮袋交给你，你们赶往港务办公室核对签发记录。', { clockAdvance: 15, publicPatch: publicPatch({ objective: '在档案被封存前核对封港调令。', knownPeopleIds: ['person_mu', 'person_lin', 'person_wei'], knownClueIds: ['clue_notice'], itemIds: ['item_postbag', 'item_order_copy'], crisisIds: ['crisis_tide', 'crisis_lockdown'] }), hiddenPatch: hiddenPatch(['chose_office']), nextSceneId: 'port_office' }),
                move('gate_to_pump', '先检查潮门故障', '你沿检修道奔向旧泵房，小牧带着邮袋跟上，自动系统的红灯在雨里不断闪烁。', { clockAdvance: 15, publicPatch: publicPatch({ objective: '确认潮门自动系统为何失效。', knownPeopleIds: ['person_mu', 'person_lin', 'person_wei'], knownClueIds: ['clue_notice'], itemIds: ['item_postbag'], crisisIds: ['crisis_tide', 'crisis_pump'] }), hiddenPatch: hiddenPatch(['chose_pump']), nextSceneId: 'old_pump' }),
                move('gate_leave', '离开封港区', '你拒绝卷入港务争端，转身走向仍未封闭的高地通道；小牧只能独自抱紧邮袋。', { clockAdvance: 10, publicPatch: publicPatch({ objective: '在最后一条高地通道关闭前离开雾港。', knownPeopleIds: ['person_mu'], knownClueIds: ['clue_notice'], itemIds: [], crisisIds: ['crisis_tide'] }), hiddenPatch: hiddenPatch(['chose_leave']), nextSceneId: 'leave_harbor' }),
            ],
        },
        {
            id: 'port_office', actId: 'act_one', title: '正在封存的档案室',
            description: '办公室里的人正按魏朔命令把档案装箱。旧印、签发簿和一张缺页的疏散名单都在锁柜后。',
            location: '港务办公室', timeLabel: '22:00 前后', objective: '在封存完成前取得能被唐岑核验的证据。',
            anchors: ['港务办公室', '封港调令', '魏朔'], entryFacts: ['entered_port_office'],
            moves: [
                move('office_search_check', '查验封存档案', '这需要一次洞察判定：在值守人员封箱前，把旧印、签发时间与疏散名单串成可核验证据。', { clockAdvance: 15, attribute: 'insight', checkId: 'check_archives', publicPatch: publicPatch({ objective: '公开投骰，决定能否完整取得档案证据。', knownPeopleIds: ['person_mu', 'person_wei'], knownClueIds: ['clue_notice'], itemIds: ['item_postbag', 'item_order_copy'], crisisIds: ['crisis_tide', 'crisis_lockdown'] }), hiddenPatch: hiddenPatch(['attempted_archives']) }),
                move('archives_success', '档案判定成功后果', '你在封箱前拍下签发簿与旧印记录，并找到被扣下的完整疏散名单。', { clockAdvance: 0, revealSecretIds: ['secret_forgery', 'secret_evacuation'], publicPatch: publicPatch({ objective: '带着证据赶往巡防线，同时确认潮门破坏程度。', knownPeopleIds: ['person_mu', 'person_wei', 'person_tang'], knownClueIds: ['clue_notice', 'clue_forged_order'], itemIds: ['item_postbag', 'item_order_copy'], crisisIds: ['crisis_tide', 'crisis_lockdown', 'crisis_pump'] }), hiddenPatch: hiddenPatch(['archives_secured', 'evacuation_list_found'], { evacuation_list: true }), nextSceneId: 'old_pump' }),
                move('archives_failure', '档案判定失败后果', '封存人员夺走完整箱册，但你保住调令副本，并看清印章日期存在矛盾。', { clockAdvance: 0, revealSecretIds: ['secret_forgery'], publicPatch: publicPatch({ objective: '用不完整证据说服巡防长，赶在封锁彻底落下前行动。', knownPeopleIds: ['person_mu', 'person_wei', 'person_tang'], knownClueIds: ['clue_notice', 'clue_forged_order'], itemIds: ['item_postbag', 'item_order_copy'], crisisIds: ['crisis_tide', 'crisis_lockdown'] }), hiddenPatch: hiddenPatch(['archives_partial']), nextSceneId: 'patrol_line' }),
            ],
        },
        {
            id: 'old_pump', actId: 'act_one', title: '过热的旧泵房',
            description: '反馈柜不断打火，压力表逼近红区。线缆切口过于整齐，远处有人正把维修记录搬向焚化炉。',
            location: '旧泵房', timeLabel: '22:15–23:10', objective: '确认破坏证据，并在固定爆炸前决定把时间用在哪里。',
            anchors: ['旧泵房', '潮门反馈线', '零点风暴潮'], entryFacts: ['entered_old_pump'],
            moves: [
                move('pump_to_patrol', '带证据赶往巡防线', '你保存被剪断的线头与维修编号，放弃修复必然爆炸的泵体，赶去阻止旧港封锁。', { clockAdvance: 25, revealSecretIds: ['secret_sabotage'], publicPatch: publicPatch({ objective: '让唐岑相信调令和故障都有人为问题。', knownPeopleIds: ['person_mu', 'person_wei', 'person_tang'], knownClueIds: ['clue_cut_wire'], itemIds: ['item_postbag', 'item_order_copy'], crisisIds: ['crisis_tide', 'crisis_lockdown', 'crisis_pump'] }), hiddenPatch: hiddenPatch(['wire_evidence_secured']), nextSceneId: 'patrol_line' }),
                move('pump_follow_signal', '循检修码去钟楼', '线路里传来三短一长的检修码；你确认信号源在钟楼，立即转向寻找林岚。', { clockAdvance: 25, publicPatch: publicPatch({ objective: '沿检修码找到失踪的工程师林岚。', knownPeopleIds: ['person_mu', 'person_lin', 'person_wei'], knownClueIds: ['clue_cut_wire', 'clue_signal'], itemIds: ['item_postbag'], crisisIds: ['crisis_tide', 'crisis_pump'] }), hiddenPatch: hiddenPatch(['heard_lin_signal']), nextSceneId: 'bell_tower' }),
                move('pump_wait_explosion', '留下抢救旧泵房', '你留下尝试压住持续上升的泵压；23:10 的爆炸仍然发生，但你的预警让附近检修员及时撤开。', { clockAdvance: 75, publicPatch: publicPatch({ objective: '爆炸已经发生；沿还能通行的维修道赶往潮门控制室。', knownPeopleIds: ['person_mu', 'person_wei', 'person_tang'], knownClueIds: ['clue_cut_wire'], itemIds: ['item_postbag'], crisisIds: ['crisis_tide', 'crisis_lockdown'] }), hiddenPatch: hiddenPatch(['stayed_for_fixed_explosion', 'pump_workers_warned']), nextSceneId: 'control_room' }),
            ],
        },
        {
            id: 'patrol_line', actId: 'act_two', title: '巡防线',
            description: '唐岑带队封住旧港路口。广播重复魏朔的命令，泵房方向的压力警报正盖过雨声。',
            location: '旧港巡防线', timeLabel: '22:30–23:30', objective: '让巡防队承认风险、放行疏散并为控制室争取时间。',
            anchors: ['唐岑', '巡防队', '旧港封锁', '小牧'], entryFacts: ['entered_patrol_line'],
            moves: [
                move('patrol_persuade_check', '说服唐岑核验并疏散', '这需要一次交涉判定：以现有证据承担后果，要求唐岑违抗尚未证伪的正式调令。', { clockAdvance: 20, attribute: 'rapport', checkId: 'check_tang', publicPatch: publicPatch({ objective: '公开投骰，决定旧港能否及时开始完整疏散。', knownPeopleIds: ['person_mu', 'person_tang', 'person_wei'], knownClueIds: ['clue_notice'], itemIds: ['item_postbag', 'item_order_copy'], crisisIds: ['crisis_tide', 'crisis_lockdown'] }), hiddenPatch: hiddenPatch(['attempted_tang']) }),
                move('tang_success', '交涉判定成功后果', '唐岑核对证据后撕下封锁令，派人按邮袋名单分区疏散旧港，并为你打开钟楼通道。', { clockAdvance: 0, publicPatch: publicPatch({ objective: '救出林岚并取得人工分流方法。', knownPeopleIds: ['person_mu', 'person_tang', 'person_lin', 'person_wei'], knownClueIds: ['clue_notice', 'clue_forged_order'], itemIds: ['item_postbag', 'item_order_copy'], crisisIds: ['crisis_tide', 'crisis_pump'] }), hiddenPatch: hiddenPatch(['evacuated_old_harbor', 'tang_allied'], { old_harbor_evacuating: true }), nextSceneId: 'bell_tower' }),
                move('tang_failure', '交涉判定失败后果', '唐岑不肯仅凭现有材料撤线，但把爆炸救援交给副手，允许你独自通过维修道去控制室。', { clockAdvance: 0, publicPatch: publicPatch({ objective: '在没有完整疏散的情况下赶到潮门控制室。', knownPeopleIds: ['person_mu', 'person_tang', 'person_wei'], knownClueIds: ['clue_notice'], itemIds: ['item_order_copy'], crisisIds: ['crisis_tide', 'crisis_lockdown', 'crisis_pump'] }), hiddenPatch: hiddenPatch(['tang_unconvinced']), nextSceneId: 'control_room' }),
            ],
        },
        {
            id: 'bell_tower', actId: 'act_two', title: '停摆的钟楼',
            description: '林岚被反锁在报时机下方，积水正漫过电缆。配重盒里传出金属撞击声，而零点前最后一次整点钟即将启动。',
            location: '旧港钟楼', timeLabel: '23:00–23:50', objective: '救出林岚和压力盘，再赶往潮门控制室。',
            anchors: ['旧港钟楼', '林岚', '报时机', '压力盘'], entryFacts: ['entered_bell_tower'],
            moves: [
                move('tower_rescue_check', '穿过积水救出林岚', '这需要一次身手判定：在报时机落锤前断电、打开配重盒并把林岚带出积水区。', { clockAdvance: 20, attribute: 'body', checkId: 'check_rescue', publicPatch: publicPatch({ objective: '公开投骰，决定是否能同时救出林岚并带走压力盘。', knownPeopleIds: ['person_lin', 'person_mu'], knownClueIds: ['clue_signal'], itemIds: [], crisisIds: ['crisis_tide', 'crisis_pump'] }), hiddenPatch: hiddenPatch(['attempted_rescue']) }),
                move('rescue_success', '救援判定成功后果', '你切断电源、撬开配重盒，林岚和完好的压力盘都被带出钟楼。', { clockAdvance: 0, revealSecretIds: ['secret_pressure_disk'], publicPatch: publicPatch({ objective: '带林岚和压力盘进入控制室，决定潮水去向。', knownPeopleIds: ['person_lin', 'person_mu', 'person_wei'], knownClueIds: ['clue_signal', 'clue_pressure_disk'], itemIds: ['item_pressure_disk'], crisisIds: ['crisis_tide'] }), hiddenPatch: hiddenPatch(['lin_rescued', 'pressure_disk_secured'], { pressure_disk: true, lin_available: true }), nextSceneId: 'control_room' }),
                move('rescue_failure', '救援判定失败后果', '落锤砸毁一段楼梯；林岚被救出，但压力盘边缘受损，只能执行风险更高的手动操作。', { clockAdvance: 0, revealSecretIds: ['secret_pressure_disk'], publicPatch: publicPatch({ objective: '带受损压力盘赶到控制室，接受分流风险。', knownPeopleIds: ['person_lin', 'person_mu', 'person_wei'], knownClueIds: ['clue_signal', 'clue_pressure_disk'], itemIds: ['item_pressure_disk'], crisisIds: ['crisis_tide'] }), hiddenPatch: hiddenPatch(['lin_rescued', 'pressure_disk_damaged'], { pressure_disk: true, disk_damaged: true, lin_available: true }), nextSceneId: 'control_room' }),
            ],
        },
        {
            id: 'control_room', actId: 'act_three', title: '零点潮门控制室',
            description: '外堤在风浪中震动。控制台只允许一次人工提交：导向旧港、导向仓区，或用压力盘承担高风险分流。',
            location: '潮门控制室', timeLabel: '23:30–00:00', objective: '依据已经救下的人、取得的证据与不可逆骰果，提交潮门去向。',
            anchors: ['潮门控制室', '零点风暴潮', '旧港', '仓区'], entryFacts: ['entered_control_room'],
            moves: [
                move('control_split_check', '尝试高风险分流', '这需要一次洞察判定：根据林岚的压力数据，用压力盘让旧港与仓区共同承担可控水量。', { clockAdvance: 10, attribute: 'insight', checkId: 'check_split', conditions: { allFacts: ['pressure_disk_secured'], anyFacts: [], notFacts: [] }, publicPatch: publicPatch({ objective: '公开投骰；成功可保住两区，失败会造成潮门连锁崩溃。', knownPeopleIds: ['person_lin', 'person_wei'], knownClueIds: ['clue_pressure_disk'], itemIds: ['item_pressure_disk'], crisisIds: ['crisis_tide'] }), hiddenPatch: hiddenPatch(['attempted_split']) }),
                move('split_success', '分流判定成功后果', '压力曲线在最后一秒稳定，两道泄洪渠同时开启，旧港与仓区都承受住了水量。', { clockAdvance: 0, publicPatch: publicPatch({ objective: '见证风暴后的结果。', knownPeopleIds: ['person_lin', 'person_mu', 'person_tang', 'person_wei'], knownClueIds: ['clue_pressure_disk'], itemIds: ['item_pressure_disk'], crisisIds: [] }), hiddenPatch: hiddenPatch(['both_districts_saved']), endingId: 'ending_both_saved' }),
                move('split_failure', '分流判定失败后果', '受力超过旧机构极限，分流闸链断裂；警报与洪水同时越过控制室地板。', { clockAdvance: 0, publicPatch: publicPatch({ objective: '承受已经成为事实的失败后果。', knownPeopleIds: ['person_lin', 'person_mu', 'person_tang', 'person_wei'], knownClueIds: ['clue_pressure_disk'], itemIds: [], crisisIds: [] }), hiddenPatch: hiddenPatch(['gate_cascade_failure']), endingId: 'ending_collapse' }),
                move('control_flood_warehouse', '把洪水导向仓区', '你提交仓区泄洪方案：居民区与旧港被保住，储备物资和港务资产将被海水吞没。', { clockAdvance: 10, publicPatch: publicPatch({ objective: '见证风暴后的结果。', knownPeopleIds: ['person_mu', 'person_tang', 'person_wei'], knownClueIds: [], itemIds: [], crisisIds: [] }), hiddenPatch: hiddenPatch(['warehouse_flooded']), endingId: 'ending_warehouse_flooded' }),
                move('control_flood_evacuated_harbor', '把洪水导向已疏散的旧港', '确认撤离街区后，你把洪水导向旧港低地；仓区与城市储备被保住，居民的家园承担代价。', { clockAdvance: 10, conditions: { allFacts: ['evacuated_old_harbor'], anyFacts: [], notFacts: [] }, publicPatch: publicPatch({ objective: '见证撤离完成后的城市代价。', knownPeopleIds: ['person_mu', 'person_tang', 'person_wei'], knownClueIds: ['clue_notice'], itemIds: [], crisisIds: [] }), hiddenPatch: hiddenPatch(['old_harbor_flooded_evacuated']), endingId: 'ending_harbor_evacuated' }),
                move('control_protect_warehouse_check', '冒险保住仓区', '这需要一次身手判定：在潮水抵达前手动卡住仓区闸链；成功会把水压转向无人的货运渠，失败则失去最后控制。', { clockAdvance: 10, attribute: 'body', checkId: 'check_warehouse', publicPatch: publicPatch({ objective: '公开投骰；成功保住仓区但无法避免旧港外围受淹，失败会导致全面崩溃。', knownPeopleIds: ['person_wei'], knownClueIds: [], itemIds: [], crisisIds: ['crisis_tide'] }), hiddenPatch: hiddenPatch(['attempted_warehouse']) }),
                move('warehouse_success', '保仓判定成功后果', '闸链被卡在极限位置，主仓区保住了；无人货运渠与旧港外围被洪水冲毁。', { clockAdvance: 0, publicPatch: publicPatch({ objective: '见证城市保存物资所付出的代价。', knownPeopleIds: ['person_wei', 'person_tang'], knownClueIds: [], itemIds: [], crisisIds: [] }), hiddenPatch: hiddenPatch(['warehouse_saved_outer_harbor_lost']), endingId: 'ending_warehouse_flooded' }),
                move('warehouse_failure', '保仓判定失败后果', '卡链滑脱，潮门在不均匀水压下全面失控，所有未撤离区域同时响起最高警报。', { clockAdvance: 0, publicPatch: publicPatch({ objective: '承受已经成为事实的失败后果。', knownPeopleIds: ['person_wei', 'person_tang'], knownClueIds: [], itemIds: [], crisisIds: [] }), hiddenPatch: hiddenPatch(['gate_cascade_failure']), endingId: 'ending_collapse' }),
                move('control_wait_collapse', '让最后窗口过去', '你没有在最后窗口提交任何可执行方案；零点潮头撞上外堤，失去控制的闸门按破损状态崩开。', { clockAdvance: 20, publicPatch: publicPatch({ objective: '承受延误造成的结局。', knownPeopleIds: [], knownClueIds: [], itemIds: [], crisisIds: [] }), hiddenPatch: hiddenPatch(['deadline_missed']), endingId: 'ending_collapse' }),
                move('control_walk_away', '离开控制室', '你放弃提交潮门方案，从高地检修梯离开；身后的警报继续倒数，没有人能替你撤回这个选择。', { clockAdvance: 10, publicPatch: publicPatch({ objective: '离开正在被风暴吞没的港区。', knownPeopleIds: [], knownClueIds: [], itemIds: [], crisisIds: ['crisis_tide'] }), hiddenPatch: hiddenPatch(['walked_away_at_control']), nextSceneId: 'leave_harbor' }),
            ],
        },
        {
            id: 'leave_harbor', actId: 'act_three', title: '高地通道',
            description: '最后一辆运送伤员的卡车正驶向高地。身后，雾港的警钟与潮门警报混在风里。',
            location: '雾港高地通道', timeLabel: '零点前', objective: '确认离开，并接受未参与潮门决策的后果。',
            anchors: ['雾港高地', '零点风暴潮'], entryFacts: ['entered_leave_harbor'],
            moves: [
                move('leave_confirm', '登车离开', '你登上驶向高地的卡车。雾港的最终损失由未被你改变的命令与时钟决定。', { clockAdvance: 20, publicPatch: publicPatch({ objective: '旅程结束。', knownPeopleIds: [], knownClueIds: [], itemIds: [], crisisIds: [] }), hiddenPatch: hiddenPatch(['left_harbor']), endingId: 'ending_left' }),
            ],
        },
    ],
    checks: [
        { id: 'check_archives', reason: '在档案被封存前找出伪造与疏散证据', attribute: 'insight', formula: 'd20', difficulty: 12, successStakes: '取得完整伪造证据与疏散名单。', failureStakes: '只保住不完整证据，封锁继续收紧。', successMoveId: 'archives_success', failureMoveId: 'archives_failure' },
        { id: 'check_tang', reason: '让唐岑承担违抗调令并立即疏散的责任', attribute: 'rapport', formula: 'd20', difficulty: 13, successStakes: '旧港开始完整疏散，巡防线成为助力。', failureStakes: '封锁不解除，只能从维修道独自推进。', successMoveId: 'tang_success', failureMoveId: 'tang_failure' },
        { id: 'check_rescue', reason: '在积水与落锤之间救出林岚并取得压力盘', attribute: 'body', formula: 'd20', difficulty: 13, successStakes: '林岚与完好压力盘都进入控制室。', failureStakes: '林岚获救，但压力盘损坏并提高最终风险。', successMoveId: 'rescue_success', failureMoveId: 'rescue_failure' },
        { id: 'check_split', reason: '用压力盘让旧港与仓区共同承担可控水量', attribute: 'insight', formula: 'd20', difficulty: 15, successStakes: '两区都保住，风暴损失被控制。', failureStakes: '闸链连锁崩溃，未撤离者承受灾难。', successMoveId: 'split_success', failureMoveId: 'split_failure' },
        { id: 'check_warehouse', reason: '在潮头抵达前手动卡住仓区闸链', attribute: 'body', formula: 'd20', difficulty: 14, successStakes: '仓区保住，洪水转向无人货运渠与旧港外围。', failureStakes: '潮门全面失控，所有低地同时受灾。', successMoveId: 'warehouse_success', failureMoveId: 'warehouse_failure' },
    ],
    endings: [
        { id: 'ending_both_saved', title: '两道晨光', summary: '旧港与仓区都挺过零点潮。分流记录与破坏证据被保存，魏朔无法再把灾难称作天意。', epilogue: '天亮时，林岚在潮门边重新校准那枚压力盘；雾港第一次把所有人的名字写进同一份报告。' },
        { id: 'ending_warehouse_flooded', title: '盐水里的账本', summary: '旧港居民获救，仓区与物资被洪水吞没。城市活了下来，却必须公开讨论谁曾把货物放在人命之前。', epilogue: '小牧把最后一封疏散通知贴在泡水的仓门上，通知背面写满了幸存者的名字。' },
        { id: 'ending_harbor_evacuated', title: '没有人的旧港', summary: '完整疏散让旧港的街巷代替居民承受洪水。仓区保住，但数代人的家园沉入咸水。', epilogue: '退潮后，唐岑把封锁牌拆下来当作临时桥板；没有人称这是无损的胜利。' },
        { id: 'ending_collapse', title: '零点之后没有钟声', summary: '潮门失控，低地付出最沉重的代价。此前完成的疏散与救援仍决定了有多少人走出风暴。', epilogue: '多年后，人们仍会争论那一夜是谁的错；不可争辩的是已经公开的骰果与错过的时间。' },
        { id: 'ending_left', title: '从高地回望', summary: '你离开了潮门决策。雾港依照既有命令迎接风暴，而那些未被揭开的事实继续留在水下。', epilogue: '卡车越过山脊时，最后一声警钟被风吹散；离开也是一个不会自行撤回的选择。' },
    ],
    startSceneId: 'customs_gate',
};

export const FOG_HARBOR_SCENARIO = finalizeScenario(draft);
